//TORE Categories
const STAKEHOLDER_GOAL = "Goal";
const STAKEHOLDER_TASK = "Task";
const SUPPORTED_STAKEHOLDER = "Stakeholder";
const DOMAIN_DATA = "Domain Data";
const INTERACTION_DATA = "Interaction Data";
const SYSTEM_FUNCTION = "System Function";
const WORKSPACE = "Workspace";
const SOFTWARE = "Software";
const INTERNAL_DATA = "Internal Data";

//TORE Relationships 
const COMMUNICATES_WITH = "communicates with";
const EXCHANGES_WITH = "exchanges with";
const WORKS_WITH = "works with";
const INPUTS = "inputs";
const ACCESSES = "accesses";
const SELECTS = "selects";
const UTILIZES = "utilizes";
const USES = "uses";
const OUTPUTS = "outputs";
const ARRANGES = "arranges";
const PROVIDES = "provides";
const PROCESSES = "processes";

export const tore_codes = [
    STAKEHOLDER_GOAL,
    STAKEHOLDER_TASK,
    SUPPORTED_STAKEHOLDER,
    DOMAIN_DATA,
    INTERACTION_DATA,
    SYSTEM_FUNCTION,
    WORKSPACE,
    SOFTWARE,
    INTERNAL_DATA
]

export const tore_relationships = {
    [COMMUNICATES_WITH]: [SUPPORTED_STAKEHOLDER, SUPPORTED_STAKEHOLDER],
    [EXCHANGES_WITH]: [SUPPORTED_STAKEHOLDER, SUPPORTED_STAKEHOLDER],
    [WORKS_WITH]: [SUPPORTED_STAKEHOLDER, DOMAIN_DATA],
    [INPUTS]: [SUPPORTED_STAKEHOLDER, INTERACTION_DATA],
    [ACCESSES]: [SUPPORTED_STAKEHOLDER, INTERACTION_DATA],
    [SELECTS]: [SUPPORTED_STAKEHOLDER, WORKSPACE],
    [UTILIZES]: [SUPPORTED_STAKEHOLDER, SYSTEM_FUNCTION],
    [USES]: [SUPPORTED_STAKEHOLDER, SOFTWARE],
    [OUTPUTS]: [SOFTWARE, INTERACTION_DATA],
    [ARRANGES]: [SOFTWARE, WORKSPACE],
    [PROVIDES]: [SOFTWARE, SYSTEM_FUNCTION],
    [PROCESSES]: [SOFTWARE,INTERNAL_DATA]
}

export const tore_locations = {
    [STAKEHOLDER_GOAL]: [0,0],
    [STAKEHOLDER_TASK]: [300,0],
    [SUPPORTED_STAKEHOLDER]: [0,400],
    [DOMAIN_DATA]: [800, 200],
    [INTERACTION_DATA]: [1400, 800],
    [SYSTEM_FUNCTION]: [1400, 1000],
    [WORKSPACE]: [1400, 600],
    [SOFTWARE]: [800, 600],
    [INTERNAL_DATA]: [1400, 400],
    [COMMUNICATES_WITH]: [-200, 300],
    [EXCHANGES_WITH]: [-200, 550],
    [WORKS_WITH]: [450, 250],
    [INPUTS]: [450, 700],
    [ACCESSES]: [450, 850],
    [SELECTS]: [450, 400],
    [UTILIZES]: [450, 1000],
    [USES]: [450, 550],
    [OUTPUTS]: [1150, 800],
    [ARRANGES]: [1150, 650],
    [PROVIDES]: [1150, 950],
    [PROCESSES]: [1150, 500]
}