== ri-visualization image:https://img.shields.io/badge/License-EPL%202.0-blue.svg["EPL 2.0", link="https://www.eclipse.org/legal/epl-2.0/"]
This component was created as a result of the OpenReq project and then later expanded by members of the UVL project.

== Technical description
=== What does the microservice do
The ri-visualization microservice is a web-based service for analysing user feedback from different sources (manual upload, reddit, app reviews, tweets) both automatically and manually.

[red]#Please be aware that this ms collects user interaction data. To turn it off, please consider removing line 9 in /public/index.html (<script src="https://api.openreq.eu/ri-logging/frontend/script"></script>)#

=== Which technologies are used
- Docker (-> https://www.docker.com/)
- vuejs (-> https://github.com/vuejs)
- echarts (-> https://echartsjs.com)
- vuetify (-> https://github.com/vuetifyjs/vuetify)


=== How to install it
This ms requires a running instance of ri-storage-twitter, ri-orchestration-twitter, uvl-storage-concepts and uvl-orchestration-concepts. Additional microservices can be added as desired.

Note that local running of this tool is currently not advised because of the necessary dependencies. The tool is designed to be run on a server.

=== Notes for developers 
If you are interested in using this service it is important to note, that this micro service only presents the frontend for a plethora of other micro services.

- link: https://github.com/feeduvl

All micro services share a single domain, which is defined in the `VUE_APP_BASE_URL`. You can either update this, or remove it from the build configuration and instead add your custom endoints in `src/RESTconf.js`.

== License
Free use of this software is granted under the terms of the EPL version 2 (EPL2.0).